services:
  - type: web
    name: edgar-url-shortener
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: edgar-url-shortener
          property: port